# Generated by Django 4.2 on 2023-06-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_address_event_date_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='post_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
