# Generated by Django 4.2 on 2023-10-21 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_webpage_is_default'),
        ('events', '0009_event_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='webpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='webpage.webpage'),
            preserve_default=False,
        ),
    ]
