# Generated by Django 4.2 on 2023-05-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [("server", "0001_initial")]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE server_event ADD date VARCHAR(50)",
            reverse_sql="ALTER TABLE server_event DROP COLUMN date"
        ),
    ]
