# Generated by Django 4.2 on 2023-05-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [("server", "0003_add_address_events")]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE server_event ADD price text",
            reverse_sql="ALTER TABLE server_event DROP COLUMN price"
        ),
    ]
