# Generated by Django 4.2 on 2023-06-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_event_lat_event_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='lng',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
