# Generated by Django 4.2 on 2023-08-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_event_lat_alter_event_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='post_link',
            field=models.TextField(null=True),
        ),
    ]
