# Generated by Django 4.2 on 2023-10-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_remove_event_id_event_hash_id_alter_event_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('unclassified', 'Unclassified'), ('culture', 'Culture'), ('sport', 'Sport')], default='unclassified', max_length=40),
        ),
    ]
