# Generated by Django 4.2 on 2023-10-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
