# Generated by Django 4.2 on 2023-10-23 23:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_webpage_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
