name: Setup webscraper cronjob

on:
  push:
    branches: [ "main" ]

env:
  API_BASE_URL: https://uspevents.ix.tc/api
  USERNAME: ${{ secrets.SERVER_USERNAME }}
  MODEL_BASE_PATH: /home/${{ secrets.SERVER_USERNAME }}/tcc/models
  SCRIPTS_PATH: /home/${{ secrets.SERVER_USERNAME }}/tcc/scripts
  OPERATING_SYSTEM: arm64
  LOG_LEVEL: INFO
  FACEBOOK_EMAIL: ${{ secrets.FACEBOOK_EMAIL }}
  FACEBOOK_PASSWORD: ${{ secrets.FACEBOOK_PASSWORD }}
  INSTAGRAM_EMAIL: ${{ secrets.INSTAGRAM_EMAIL }}
  INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  start_websraper_job:
    runs-on: [self-hosted, linux, ARM64, general-worker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download model from huggingface
        run: |
          mkdir -p ${{ env.MODEL_BASE_PATH }}
          wget -q --show-progress -nc -P ${{ env.MODEL_BASE_PATH }} https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/resolve/main/llama-2-13b-chat.Q5_K_M.gguf
        working-directory: ${{ env.MODEL_BASE_PATH }}

      - name: Install python dependencies to run scripts
        run: |
          cd backend
          bash initialize.sh

      - name: Install dependencies to run the cronjob and start cron service
        run: |
          if ! dpkg -l chromium-browser | grep -q "85.0.4183.83"; then
            wget http://ports.ubuntu.com/pool/universe/c/chromium-browser/chromium-browser_85.0.4183.83-0ubuntu2_arm64.deb
            sudo dpkg -i chromium-browser_85.0.4183.83-0ubuntu2_arm64.deb
          else
            echo "Chromium browser version 85.0.4183.83 is already installed."
          fi

          if ! dpkg -l chromium-chromedriver | grep -q "85.0.4183.83"; then
            wget http://ports.ubuntu.com/pool/universe/c/chromium-browser/chromium-chromedriver_85.0.4183.83-0ubuntu2_arm64.deb
            sudo dpkg -i chromium-chromedriver_85.0.4183.83-0ubuntu2_arm64.deb
          else
            echo "Chromium chromedriver version 85.0.4183.83 is already installed."
          fi

          cp /usr/bin/chromedriver /home/${{ env.USERNAME }}/.local/share/undetected_chromedriver/chromedriver_copy
          sudo apt install cron -y
          sudo systemctl enable cron

      - name: Delete the contents of the scripts folder and copy the scripts to it
        run: |
          rm -rf ${{ env.SCRIPTS_PATH }}
          mkdir -p ${{ env.SCRIPTS_PATH }}
          cp -r backend/scripts/* ${{ env.SCRIPTS_PATH }}

      - name: Setup environment variables
        run: |
          cd ${{ env.SCRIPTS_PATH }}
          cat << EOF > .env
          API_BASE_URL=${{ env.API_BASE_URL }}
          MODEL_BASE_PATH=${{ env.MODEL_BASE_PATH }}
          OPERATING_SYSTEM=${{ env.OPERATING_SYSTEM }}
          LOG_LEVEL=${{ env.LOG_LEVEL }}
          FACEBOOK_EMAIL=${{ env.FACEBOOK_EMAIL }}
          FACEBOOK_PASSWORD=${{ env.FACEBOOK_PASSWORD }}
          INSTAGRAM_EMAIL=${{ env.INSTAGRAM_EMAIL }}
          INSTAGRAM_PASSWORD=${{ env.INSTAGRAM_PASSWORD }}
          EOF

      - name: Delete existent cronjobs and add new one
        run: |
          crontab -r || true
          echo '0 */6 * * * python3.10 "${{ env.SCRIPTS_PATH }}/saveProcessedPosts.py" >> ${{ env.SCRIPTS_PATH }}/cronjob_log.txt 2>&1' > mycron
          crontab mycron
